spring:
  application:
    name: productos-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/productos-service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: rootdocker
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
